# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_version1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1109, 580)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.frame_13 = QtWidgets.QFrame(self.centralwidget)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 10))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_13.setStyleSheet("background-color: rgb(57, 57, 57);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.vboxlayout.addWidget(self.frame_13)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(400, 45))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame.setStyleSheet("background-color: rgb(90, 90, 90);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        self.frame_15.setStyleSheet("")
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setContentsMargins(0, 16, 0, 0)
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.graph_tab = QtWidgets.QPushButton(self.frame_15)
        self.graph_tab.setMinimumSize(QtCore.QSize(152, 30))
        self.graph_tab.setMaximumSize(QtCore.QSize(152, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.graph_tab.setFont(font)
        self.graph_tab.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 230, 230);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    background-color: rgb(115, 115, 115);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(230, 230, 230);\n"
"    \n"
"}")
        self.graph_tab.setObjectName("graph_tab")
        self.horizontalLayout_11.addWidget(self.graph_tab)
        self.monitor_Button = QtWidgets.QPushButton(self.frame_15)
        self.monitor_Button.setMinimumSize(QtCore.QSize(152, 30))
        self.monitor_Button.setMaximumSize(QtCore.QSize(152, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.monitor_Button.setFont(font)
        self.monitor_Button.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 230, 230);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    background-color: rgb(115, 115, 115);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(230, 230, 230);\n"
"    \n"
"}")
        self.monitor_Button.setObjectName("monitor_Button")
        self.horizontalLayout_11.addWidget(self.monitor_Button)
        self.doc_tab = QtWidgets.QPushButton(self.frame_15)
        self.doc_tab.setMinimumSize(QtCore.QSize(152, 30))
        self.doc_tab.setMaximumSize(QtCore.QSize(152, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.doc_tab.setFont(font)
        self.doc_tab.setStyleSheet("QPushButton {\n"
"    color: rgb(230, 230, 230);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    background-color: rgb(115, 115, 115);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(230, 230, 230);\n"
"    \n"
"}")
        self.doc_tab.setObjectName("doc_tab")
        self.horizontalLayout_11.addWidget(self.doc_tab)
        self.frame_22 = QtWidgets.QFrame(self.frame_15)
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_11.addWidget(self.frame_22)
        self.horizontalLayout_5.addWidget(self.frame_15)
        self.frame_6 = QtWidgets.QFrame(self.frame_10)
        self.frame_6.setMinimumSize(QtCore.QSize(125, 45))
        self.frame_6.setMaximumSize(QtCore.QSize(125, 45))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setMinimumSize(QtCore.QSize(45, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(45, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Play_Button = QtWidgets.QPushButton(self.frame_3)
        self.Play_Button.setMinimumSize(QtCore.QSize(0, 30))
        self.Play_Button.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(False)
        font.setWeight(50)
        self.Play_Button.setFont(font)
        self.Play_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Play_Button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(90, 90, 90);\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    padding-top: 1px;\n"
"}\n"
"\n"
"")
        self.Play_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/boton-de-play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play_Button.setIcon(icon)
        self.Play_Button.setObjectName("Play_Button")
        self.verticalLayout_8.addWidget(self.Play_Button)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setMinimumSize(QtCore.QSize(60, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Com_Selector = QtWidgets.QComboBox(self.frame_8)
        self.Com_Selector.setMinimumSize(QtCore.QSize(0, 0))
        self.Com_Selector.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Com_Selector.setFont(font)
        self.Com_Selector.setStyleSheet("background-color: rgb(115, 115, 115);")
        self.Com_Selector.setMaxVisibleItems(3)
        self.Com_Selector.setFrame(True)
        self.Com_Selector.setObjectName("Com_Selector")
        self.horizontalLayout_6.addWidget(self.Com_Selector)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_10)
        self.frame_7.setMinimumSize(QtCore.QSize(45, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(35, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Home_Button = QtWidgets.QPushButton(self.frame_7)
        self.Home_Button.setMinimumSize(QtCore.QSize(45, 45))
        self.Home_Button.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.Home_Button.setFont(font)
        self.Home_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Home_Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(90, 90, 90);\n"
"    color: rgb(216, 216, 216);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(136, 136, 136);\n"
"    padding-top: 1px;\n"
"   \n"
"\n"
"}\n"
"\n"
"")
        self.Home_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Home_Button.setIcon(icon1)
        self.Home_Button.setIconSize(QtCore.QSize(24, 24))
        self.Home_Button.setObjectName("Home_Button")
        self.horizontalLayout_9.addWidget(self.Home_Button)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.vboxlayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("\n"
"\n"
"/* SCROLL BARS */\n"
"\n"
"/*HORIZONTAL*/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 12px;\n"
"    margin: 0 0  0px 0 ;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    \n"
"    background-color: rgb(135, 135, 135);\n"
"    border-radius: 5px;\n"
"    min-width: 10px;    \n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:pressed{    \n"
"    background-color: rgb(165, 165, 165);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 10px;\n"
"    height: 12px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 10px;\n"
"    height: 12px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"/*important */\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{        \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/*VERTICAL*/\n"
"QScrollBar:vertical {\n"
"\n"
"    background: rgb(52, 59, 72);\n"
"    width: 25px;\n"
"    border-radius: 10px;\n"
"    margin: 0 0  0 0 ;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    \n"
"    background-color: rgb(155, 205, 255);\n"
"    border-radius: 10px;\n"
"    min-height: 10px;    \n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"    \n"
"    background-color: rgb(51, 153, 255);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed{    \n"
"    \n"
"    background-color: rgb(48, 136, 223);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"    height: 30px;    \n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:verticall {\n"
"    border: none;\n"
"    background: none;\n"
"    height: 30px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{    \n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    background :   \n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.stackedWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"background: transparent;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_32 = QtWidgets.QFrame(self.page_home)
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_32.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.frame_32)
        self.label_16.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("logos/logo-universidad-de-los-llanos.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.frame_35 = QtWidgets.QFrame(self.frame_32)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_19.addWidget(self.frame_35)
        self.label_14 = QtWidgets.QLabel(self.frame_32)
        self.label_14.setMaximumSize(QtCore.QSize(160, 70))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("logos/pixlr-bg-result.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.verticalLayout_9.addWidget(self.frame_32)
        self.frame_34 = QtWidgets.QFrame(self.page_home)
        self.frame_34.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_34.setStyleSheet("background-color: rgb(51, 153, 255);\n"
"border-radius: 10px;")
        self.frame_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_9.addWidget(self.frame_34)
        self.frame_16 = QtWidgets.QFrame(self.page_home)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.frame_16)
        self.label_13.setMinimumSize(QtCore.QSize(0, 65))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(46, 46, 46);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.frame_9 = QtWidgets.QFrame(self.page_home)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4.addWidget(self.frame_11)
        self.Solar_Button = QtWidgets.QPushButton(self.frame_9)
        self.Solar_Button.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.Solar_Button.setFont(font)
        self.Solar_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Solar_Button.setStyleSheet("QPushButton {\n"
"    color: rgb(25, 25, 25);\n"
"    \n"
"    background-color: rgb(230, 230, 230);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(73, 147, 221);\n"
"    padding-top: 2px;\n"
"    padding-right: 2px;\n"
"\n"
"}\n"
"")
        self.Solar_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/solar-panel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Solar_Button.setIcon(icon2)
        self.Solar_Button.setIconSize(QtCore.QSize(128, 128))
        self.Solar_Button.setDefault(False)
        self.Solar_Button.setFlat(False)
        self.Solar_Button.setObjectName("Solar_Button")
        self.horizontalLayout_4.addWidget(self.Solar_Button)
        self.Wind_button = QtWidgets.QPushButton(self.frame_9)
        self.Wind_button.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.Wind_button.setFont(font)
        self.Wind_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Wind_button.setStyleSheet("QPushButton {\n"
"    color: rgb(25, 25, 25);\n"
"    \n"
"    background-color: rgb(230, 230, 230);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(73, 147, 221);\n"
"    padding-top: 2px;\n"
"    padding-right: 2px;\n"
"\n"
"}\n"
"")
        self.Wind_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/wind-energy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wind_button.setIcon(icon3)
        self.Wind_button.setIconSize(QtCore.QSize(128, 128))
        self.Wind_button.setObjectName("Wind_button")
        self.horizontalLayout_4.addWidget(self.Wind_button)
        self.Hydrogen_button = QtWidgets.QPushButton(self.frame_9)
        self.Hydrogen_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Hydrogen_button.sizePolicy().hasHeightForWidth())
        self.Hydrogen_button.setSizePolicy(sizePolicy)
        self.Hydrogen_button.setMinimumSize(QtCore.QSize(0, 150))
        self.Hydrogen_button.setSizeIncrement(QtCore.QSize(0, 0))
        self.Hydrogen_button.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.Hydrogen_button.setFont(font)
        self.Hydrogen_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Hydrogen_button.setStyleSheet("QPushButton {\n"
"    color: rgb(25, 25, 25);\n"
"    \n"
"    background-color: rgb(230, 230, 230);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(73, 147, 221);\n"
"    padding-top: 2px;\n"
"    padding-right: 2px;\n"
"\n"
"}\n"
"")
        self.Hydrogen_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/h2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Hydrogen_button.setIcon(icon4)
        self.Hydrogen_button.setIconSize(QtCore.QSize(128, 128))
        self.Hydrogen_button.setObjectName("Hydrogen_button")
        self.horizontalLayout_4.addWidget(self.Hydrogen_button)
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_4.addWidget(self.frame_12)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.frame_33 = QtWidgets.QFrame(self.page_home)
        self.frame_33.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_33.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_15.setContentsMargins(0, 35, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.frame_33)
        self.label_15.setMaximumSize(QtCore.QSize(140, 50))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("logos/pixlr-bg-result (1).png"))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.verticalLayout_9.addWidget(self.frame_33)
        self.stackedWidget.addWidget(self.page_home)
        self.page_graph = QtWidgets.QWidget()
        self.page_graph.setStyleSheet("")
        self.page_graph.setObjectName("page_graph")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.page_graph)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_28 = QtWidgets.QFrame(self.page_graph)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.MplWidget = MplWidget(self.frame_28)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.MplWidget.setFont(font)
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_12.addWidget(self.MplWidget)
        self.frame_14 = QtWidgets.QFrame(self.frame_28)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_14.setStyleSheet("background-color: rgb(244, 244, 244);\n"
"border-radius: 10;\n"
"\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_14)
        self.label_4.setMinimumSize(QtCore.QSize(120, 15))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.frame_14)
        self.label_6.setMinimumSize(QtCore.QSize(120, 15))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_3 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.frame_14)
        self.horizontalScrollBar.setMinimumSize(QtCore.QSize(95, 12))
        self.horizontalScrollBar.setMaximumSize(QtCore.QSize(95, 12))
        self.horizontalScrollBar.setStyleSheet("")
        self.horizontalScrollBar.setMinimum(1)
        self.horizontalScrollBar.setMaximum(5)
        self.horizontalScrollBar.setSingleStep(1)
        self.horizontalScrollBar.setPageStep(1)
        self.horizontalScrollBar.setProperty("value", 1)
        self.horizontalScrollBar.setTracking(True)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayout_7.addWidget(self.horizontalScrollBar)
        self.label_5 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(self.frame_14)
        self.horizontalScrollBar_2.setMinimumSize(QtCore.QSize(95, 12))
        self.horizontalScrollBar_2.setMaximumSize(QtCore.QSize(95, 12))
        self.horizontalScrollBar_2.setStyleSheet("")
        self.horizontalScrollBar_2.setMinimum(1)
        self.horizontalScrollBar_2.setMaximum(3)
        self.horizontalScrollBar_2.setPageStep(1)
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.horizontalLayout_7.addWidget(self.horizontalScrollBar_2)
        self.Adjust_YButton = QtWidgets.QPushButton(self.frame_14)
        self.Adjust_YButton.setMinimumSize(QtCore.QSize(30, 12))
        self.Adjust_YButton.setMaximumSize(QtCore.QSize(30, 12))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(7)
        self.Adjust_YButton.setFont(font)
        self.Adjust_YButton.setStyleSheet("QPushButton {\n"
"    color: rgb(25, 25, 25);\n"
"    \n"
"    background-color: rgb(230, 230, 230);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(73, 147, 221);\n"
"    \n"
"}")
        self.Adjust_YButton.setObjectName("Adjust_YButton")
        self.horizontalLayout_7.addWidget(self.Adjust_YButton)
        self.verticalLayout_12.addWidget(self.frame_14)
        self.horizontalLayout_18.addWidget(self.frame_28)
        self.frame_31 = QtWidgets.QFrame(self.page_graph)
        self.frame_31.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_31.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_31.setStyleSheet("")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_29 = QtWidgets.QFrame(self.frame_31)
        self.frame_29.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_29.setStyleSheet("background-color: rgb(105, 105, 105);\n"
"border: 0px solid;\n"
"border-radius: 10px;\n"
"")
        self.frame_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_11.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_29)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 2px solid rgb(230, 230, 230);\n"
"    background-color: rgb(244, 244, 244);\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: 0px solid black;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: rgb(25, 25, 25);\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    \n"
"     border-bottom: 1px solid rgb(230, 230, 230);\n"
"    color: rgb(230, 230, 230);\n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    \n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 4px 10px 4px 10px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 20ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.save_tab = QtWidgets.QWidget()
        self.save_tab.setObjectName("save_tab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.save_tab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_17 = QtWidgets.QFrame(self.save_tab)
        self.frame_17.setMinimumSize(QtCore.QSize(50, 30))
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_17.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.save_as = QtWidgets.QPushButton(self.frame_17)
        self.save_as.setMinimumSize(QtCore.QSize(30, 30))
        self.save_as.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.save_as.setFont(font)
        self.save_as.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(216, 216, 216);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(136, 136, 136);\n"
"    padding-top: 1px;\n"
"    \n"
"\n"
"}\n"
"")
        self.save_as.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/save-icon-5404.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_as.setIcon(icon5)
        self.save_as.setIconSize(QtCore.QSize(18, 18))
        self.save_as.setObjectName("save_as")
        self.horizontalLayout_17.addWidget(self.save_as)
        self.Filename = QtWidgets.QLineEdit(self.frame_17)
        self.Filename.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.Filename.setFont(font)
        self.Filename.setStyleSheet("background-color: rgb(120, 120, 120);\n"
"padding-left: 10px;")
        self.Filename.setText("")
        self.Filename.setObjectName("Filename")
        self.horizontalLayout_17.addWidget(self.Filename)
        self.horizontalLayout_16.addWidget(self.frame_17)
        self.tabWidget.addTab(self.save_tab, "")
        self.load_tab = QtWidgets.QWidget()
        self.load_tab.setObjectName("load_tab")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.load_tab)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_18 = QtWidgets.QFrame(self.load_tab)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_20.setSpacing(2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(216, 216, 216);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(136, 136, 136);\n"
"    padding-top: 1px;\n"
"    \n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon6)
        self.pushButton_2.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_20.addWidget(self.pushButton_2)
        self.save = QtWidgets.QPushButton(self.frame_18)
        self.save.setMinimumSize(QtCore.QSize(30, 30))
        self.save.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.save.setFont(font)
        self.save.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(216, 216, 216);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(136, 136, 136);\n"
"    padding-top: 1px;\n"
"    \n"
"\n"
"}\n"
"")
        self.save.setText("")
        self.save.setIcon(icon5)
        self.save.setIconSize(QtCore.QSize(18, 18))
        self.save.setObjectName("save")
        self.horizontalLayout_20.addWidget(self.save)
        self.file_selector = QtWidgets.QComboBox(self.frame_18)
        self.file_selector.setMinimumSize(QtCore.QSize(87, 20))
        self.file_selector.setMaximumSize(QtCore.QSize(210, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.file_selector.setFont(font)
        self.file_selector.setStyleSheet("QComboBox{    \n"
"    color: rgb(230, 230, 230);\n"
"    border: 1px solid rgb(57, 57, 57);\n"
"    border-radius: 3px;\n"
"    padding: 1px 4px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 18px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: rgb(57, 57, 57);\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 1px solid rgb(57, 57, 57);\n"
"    border-bottom-left-radius: 3px; \n"
"    border-bottom-right-radius: 3px;\n"
"    color: rgb(40, 40, 40);\n"
"    \n"
"    \n"
"}")
        self.file_selector.setFrame(True)
        self.file_selector.setObjectName("file_selector")
        self.file_selector.addItem("")
        self.horizontalLayout_20.addWidget(self.file_selector)
        self.pushButton = QtWidgets.QPushButton(self.frame_18)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(136, 136, 136);\n"
"    padding-top: 1px;\n"
"    \n"
"\n"
"}\n"
"\n"
"")
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/trash-can.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(18, 18))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_20.addWidget(self.pushButton)
        self.horizontalLayout_14.addWidget(self.frame_18)
        self.tabWidget.addTab(self.load_tab, "")
        self.verticalLayout_11.addWidget(self.tabWidget)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_29)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {    \n"
"    \n"
"    background-color: rgb(244, 244, 244);    \n"
"    padding: 5px;\n"
"    border-radius: 8px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 0px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    \n"
"    background-color: rgb(51, 153, 255);\n"
"}\n"
"\n"
"/*VERTICAL*/\n"
"QScrollBar:vertical {\n"
"\n"
"    background: rgb(52, 59, 72);\n"
"    width: 12px;\n"
"    border: solid \n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"        \n"
"    background-color: rgb(135, 135, 135);\n"
"    border-radius: 10px;\n"
"    min-height: 10px;    \n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"    \n"
"    background-color: rgb(150, 150, 150);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed{    \n"
"    background-color: rgb(165, 165, 165);\n"
"}\n"
"\n"
"QScrollBar::sub-line:verticall {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    height: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{    \n"
"    background: rgb(105, 105, 105);   \n"
"    border-radius: 10px; \n"
"}")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(21)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(118)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.verticalLayout_11.addWidget(self.tableWidget)
        self.verticalLayout_4.addWidget(self.frame_29)
        self.horizontalLayout_18.addWidget(self.frame_31)
        self.stackedWidget.addWidget(self.page_graph)
        self.page_doc = QtWidgets.QWidget()
        self.page_doc.setObjectName("page_doc")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_doc)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page_doc)
        self.scrollArea.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(174, 227, 255, 255), stop:0.142045 rgba(255, 255, 255, 255));\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 771, 2175))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_23.setStyleSheet("background-color: none;")
        self.frame_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.frame_23)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(600, 200))
        self.label_9.setStyleSheet("")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Logo-Horizon-Educational-Blue.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.verticalLayout_7.addWidget(self.frame_23)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 70))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.frame_26 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_26.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_26.setStyleSheet("background-color: none;")
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.frame_26)
        self.label_12.setMinimumSize(QtCore.QSize(400, 320))
        self.label_12.setMaximumSize(QtCore.QSize(400, 320))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("prod_9307660532-removebg-preview.png"))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.verticalLayout_7.addWidget(self.frame_26)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: none;")
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.frame_25 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_25.setStyleSheet("background-color: none;")
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_7.addWidget(self.frame_25)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: none;")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_doc)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(105, 105, 105);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DocArea = QtWidgets.QScrollArea(self.frame_4)
        self.DocArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DocArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.DocArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.DocArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DocArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.DocArea.setWidgetResizable(True)
        self.DocArea.setObjectName("DocArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 290, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(230, 230, 230);")
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(False)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.DocArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.DocArea)
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 15))
        self.frame_20.setStyleSheet("border-top-style: solid;\n"
"border-color: rgb(230, 230, 230);\n"
"border-width: 0.5px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.doc_plus = QtWidgets.QPushButton(self.frame_20)
        self.doc_plus.setMinimumSize(QtCore.QSize(40, 0))
        self.doc_plus.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.doc_plus.setFont(font)
        self.doc_plus.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(155, 155, 155);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(230, 230, 230);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed{    \n"
"    color: rgb(51, 153, 255);    \n"
"}\n"
"\n"
"")
        self.doc_plus.setAutoExclusive(False)
        self.doc_plus.setObjectName("doc_plus")
        self.horizontalLayout_8.addWidget(self.doc_plus)
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_8.addWidget(self.frame_21)
        self.verticalLayout_6.addWidget(self.frame_20)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_27 = QtWidgets.QFrame(self.frame_2)
        self.frame_27.setMinimumSize(QtCore.QSize(45, 0))
        self.frame_27.setMaximumSize(QtCore.QSize(45, 16777215))
        self.frame_27.setStyleSheet("background-color: rgb(97, 97, 97);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Print_Button = QtWidgets.QPushButton(self.frame_27)
        self.Print_Button.setMinimumSize(QtCore.QSize(45, 45))
        self.Print_Button.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Print_Button.setFont(font)
        self.Print_Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(216, 216, 216);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(136, 136, 136);\n"
"    padding-top: 1px;\n"
"    \n"
"}\n"
"")
        self.Print_Button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Print_Button.setIcon(icon8)
        self.Print_Button.setIconSize(QtCore.QSize(24, 24))
        self.Print_Button.setObjectName("Print_Button")
        self.verticalLayout_5.addWidget(self.Print_Button)
        self.doc_Button = QtWidgets.QPushButton(self.frame_27)
        self.doc_Button.setMinimumSize(QtCore.QSize(45, 45))
        self.doc_Button.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.doc_Button.setFont(font)
        self.doc_Button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(216, 216, 216);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(136, 136, 136);\n"
"    padding-top: 1px;\n"
"    \n"
"\n"
"}\n"
"\n"
"")
        self.doc_Button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/book-icon-139.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.doc_Button.setIcon(icon9)
        self.doc_Button.setIconSize(QtCore.QSize(24, 24))
        self.doc_Button.setAutoExclusive(False)
        self.doc_Button.setObjectName("doc_Button")
        self.verticalLayout_5.addWidget(self.doc_Button)
        self.ToggleButton = QtWidgets.QPushButton(self.frame_27)
        self.ToggleButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Siemens Slab Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.ToggleButton.setFont(font)
        self.ToggleButton.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"    color: rgb(216, 216, 216);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(136, 136, 136);\n"
"    padding-top: 1px;\n"
"    \n"
"\n"
"}\n"
"\n"
"")
        self.ToggleButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/manual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToggleButton.setIcon(icon10)
        self.ToggleButton.setIconSize(QtCore.QSize(22, 22))
        self.ToggleButton.setFlat(False)
        self.ToggleButton.setObjectName("ToggleButton")
        self.verticalLayout_5.addWidget(self.ToggleButton)
        self.frame_30 = QtWidgets.QFrame(self.frame_27)
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_5.addWidget(self.frame_30)
        self.horizontalLayout.addWidget(self.frame_27)
        self.vboxlayout.addWidget(self.frame_2)
        self.frame_19 = QtWidgets.QFrame(self.centralwidget)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 15))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 15))
        self.frame_19.setStyleSheet("background-color: rgb(255, 243, 65);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.frame_19)
        self.label_7.setMinimumSize(QtCore.QSize(0, 15))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.vboxlayout.addWidget(self.frame_19)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.graph_tab.setText(_translate("MainWindow", "Grafica"))
        self.monitor_Button.setText(_translate("MainWindow", "Monitor"))
        self.doc_tab.setText(_translate("MainWindow", "Doc"))
        self.label_13.setText(_translate("MainWindow", "Monitoreo en Tiempo Real"))
        self.label_4.setText(_translate("MainWindow", "Voltaje: "))
        self.label_6.setText(_translate("MainWindow", "Tiempo transc :"))
        self.label_3.setText(_translate("MainWindow", "Time/div"))
        self.label_5.setText(_translate("MainWindow", "Volt/div"))
        self.Adjust_YButton.setText(_translate("MainWindow", "Auto"))
        self.Filename.setPlaceholderText(_translate("MainWindow", "Nombre de la Hoja"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.save_tab), _translate("MainWindow", "Guardar en nueva Hoja"))
        self.file_selector.setCurrentText(_translate("MainWindow", "Escoger hoja.."))
        self.file_selector.setItemText(0, _translate("MainWindow", "Escoger hoja.."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.load_tab), _translate("MainWindow", "Guardar en Hoja existente"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Fecha(a/m/d)"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Energia G(w/h)"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Duracion(h:m:s) "))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>El Set educativo de energías renovables <span style=\" font-weight:600; color:#1688dc;\">FCJJ-27</span> es un sistema modular diseñado para realizar experimentos y demostrar el funcionamiento y entendimiento de una forma práctica de la tecnología disponible hoy en día para la obtención de <span style=\" font-weight:600; color:#1688dc;\">energías limpias</span>, suministrando un equipo completo en miniatura para producir y experimentar con la obtención de la energía a escala, como en los laboratorios.</p><p>Con este completo kit puede construir un sistema para la obtención de energía renovable en miniatura completo para la experimentación y demostración. </p><p>Este conjunto en sí constituye un completo sistema de trabajo real a escala incorporando, <span style=\" font-weight:600; color:#1688dc;\">un aerogenerador</span><span style=\" font-weight:600;\">, </span><span style=\" font-weight:600; color:#1688dc;\">un panel solar fotovoltaico</span><span style=\" font-weight:600;\">, </span><span style=\" font-weight:600; color:#1688dc;\">un electrolizador</span><span style=\" font-weight:600;\">, </span>una pila de combustible PEM y un sistema de almacenamiento de hidrógeno. </p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Un sistema que pretende alentar al usuario aprender las diferentes formas de generación de energía y experimentar con diferentes configuraciones gracias a su sistema modular. </p><p>Aprenda a generar energía limpia paso a paso y experimente con diferentes configuraciones para comprender de principio a fin de cómo obtener energía limpia sin emisiones de CO₂. </p><p>Este documento contiene una breve reseña sobre la energía renovable, instrucciones sobre experimentos, guía de montaje y manual de uso del programa.</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#1688dc;\">CUENTA CON LOS SIGUIENTES ELEMENTOS:</span></p><p>1. Aerogenerador. </p><p>2. Célula Fotovoltaica - Solar</p><p>3. Electrolizador.</p><p>4. Célula de Combustible PEM de Hidrógeno H2.</p><p>5. Sistema de depósito de Hidrógeno.</p><p><br/></p><p><span style=\" font-size:16pt; font-weight:600; color:#1688dc;\">EXPERIMENTOS Y ACTIVIDADES QUE SE PUEDEN REALIZAR: </span></p><p><br/></p><p><span style=\" font-weight:600; color:#3399ff;\">Experimentos de energía solar </span></p><p>1. El efecto del calor en los paneles solares </p><p>2. El efecto de la sombra en los paneles solares </p><p>3. El efecto del ángulo de inclinación en los paneles solares </p><p>4. Encontrar el punto de máxima potencia del panel solar </p><p><br/></p><p><span style=\" font-weight:600; color:#3399ff;\">Energía de experimentos de hidrógeno</span></p><p>1. Modo de electrólisis que genera H2 y O2 </p><p>2. Modo de pila de combustible que genera electricidad a partir de H2 y O2 </p><p>3. Determinación del voltaje mínimo de descomposición del agua </p><p>4. Estados de polarización de las pilas de combustible de hidrógeno </p><p><br/></p><p><span style=\" font-weight:600; color:#3399ff;\">Experimentos de energía eólica </span></p><p>1. ¿Cuántas hojas son las mejores: 1, 2, 3 ... más? </p><p>2. Uso de tres formas diferentes de hojas curvas </p><p>3. Usando cuchillas que usted mismo hace </p><p>4. Eficiencias de la turbina </p><p>5. Medición de RPM </p><p>6. Ajuste para la máxima potencia </p><p>7. Cómo afecta el ángulo o la inclinación de la hoja a la potencia de salida </p><p>8. Para generar hidrógeno </p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">KIT EDUCATIONAL HORIZON FCJJ-37</span></p><p><span style=\" font-size:14pt;\">GUIA DE USUARIO</span></p><p>__________________________________</p><p><span style=\" font-size:10pt;\">Esta ventana contiene informacion<br/>referente a lo que se muestra en la <br/>ventana actualmente, para navegar<br/>por las practicas posibles haga click en<br/>alguna de las 3 opciones de la izquierda<br/>que lo llevaran al modo monitor,<br/>puede siempre volver al inicio con el <br/>icono de casaen la esquina superior <br/>derecha,tambien puede explorar las <br/>opciones de la derecha disponibles: </span></p><p><span style=\" font-size:10pt;\">La carpeta para guardar o cargar datos <br/>capturados (solo disponible estando en<br/>modo monitor).<br/>El libro que abre la documentacion <br/>disponible sobre los experimentos y las<br/>tematicas estudiadas.<br/>El manual el cual es esta ventana que<br/>guias e instrucciones referentes a la<br/>ventana en que se encuentre.<br/></span></p><p><br/></p></body></html>"))
        self.doc_plus.setText(_translate("MainWindow", " # Doc"))
        self.label_7.setText(_translate("MainWindow", " # Error Prompt"))
from mplwidget import MplWidget
import Doc images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
